config/routes.rb
Rails.application.routes.draw do

  
  resources :boards do
    resources :posts
    resources :links
    resources :videos
  end

  root 'boards#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :board
end

app/controllers/videos_controller.rb
VideoInfo.provider_api_keys = { youtube: 'AIzaSyAdoZSg-_HK4ZWzg487jFBZ__gvpuU_L5k', vimeo: '963948cf67b44888a16404c0085dbf2f'}

class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :set_board

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @iframe = @video.iFrame_Source.html_safe
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.board_id = @board.id

    urlVideo = VideoInfo.new(@video.source)


    @video.iFrame_Source = urlVideo.embed_code
    @video.title = urlVideo.title
    @video.date = urlVideo.date
    @video.provider = urlVideo.provider
    @video.description = urlVideo.description
    @video.smaller_thumbnail = urlVideo.thumbnail_small
    @video.larger_thumbnail = urlVideo.thumbnail_large


    respond_to do |format|
      if @video.save
        format.html { redirect_to board_video_path(@board, @video), notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to board_video_path(@board, @video), notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    def set_board
      @board = Board.find(params[:board_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :source, :board_id, :iFrame_Source, :type)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for([@board,@video]) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Source</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.source %></td>
        <td><%= video.board_id %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

 <div><%= image_tag @video.larger_thumbnail, :class => "style_image" %></div>

 <div>
 	<%= @iframe %>
 </div>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Board id:</strong>
  <%= @video.board_id %>
</p>

<p>
  <strong>Source:</strong>
  <%= @video.source %>
</p>

<p>
  <strong>Board:</strong>
  <%= @video.board_id %>
</p>

<p>
  <strong>iframe:</strong>
  <%= @video.iFrame_Source %>
</p>

<p>
  <strong>date:</strong>
  <%= @video.date %>
</p>

<p>
  <strong>provider:</strong>
  <%= @video.provider %>
</p>

<p>
  <strong>description:</strong>
  <%= @video.description %>
</p>

<%= link_to 'Edit', edit_board_video_path(@board, @video) %> |
<%= link_to 'Back', root_path %>