config/routes.rb
Rails.application.routes.draw do

  
  resources :boards do
    resources :posts
    resources :links
    resources :videos
  end

  root 'boards#index'

end

app/models/board.rb
class Board < ActiveRecord::Base

	has_many :posts
	has_many :links
	has_many :videos
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :sort_content, only: [:index]

  # GET /boards
  # GET /boards.json



  def index
    @boards = Board.all


    @posts = Post.all
    @links = Link.all
    @videos = Video.all


   
    puts @sorted_content

    #@boards.each do |board|
     # @posts = Post.where(board_id: board.id).order("created_at DESC")
     # @links = Link.where(board_id: board.id).order("created_at DESC")
     # @videos = Video.where(board_id: board.id).order("created_at DESC")
    #end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    

    def sort_content
      posts = Post.all
      links = Link.all
      videos = Video.all

      @content = posts + links + videos
      @sorted_content = @content.sort_by{ |obj| obj.created_at }.reverse!
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper

	

end

app/views/boards/_action.html.erb
<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">x</span>

    <%= board.id %>

   	<ul>
		<li><%= link_to 'New Post', new_board_post_path(board), class: "actionBtn" %></li>
		<li><%= link_to 'New Article', new_board_link_path(board), class: "actionBtn"  %></li>
		<li><%= link_to 'New Video', new_board_video_path(board), class: "actionBtn"  %></li>

	</ul>	
  </div>

</div>

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div id="bg">
    <img src="images/syria.jpg" alt="">
</div>

<div id="logo">
  <img src="images/red7.png">
</div>

<!-- End of background designs -->










<p id="notice"><%= notice %></p>
<%= link_to 'New Board', new_board_path %>

<br>


<article class="tabs">
  <ul>
    <% @boards.each do |board| %>
          <li><a data-id-number = "tt<%= board.id %>" href="#tt<%= board.id%>"> <%= board.title %> </a></li>

    <% end %>
  </ul>

<% @boards.each do |board| %>
  <%= render partial: 'action', locals: {board: board } %>


  <section id="tt<%= board.id %>" > 

    <div class="boardConfig" > <!-- Beginning of board config -->
     
      <div class="postActions"> 
          <!-- Trigger/Open The Modal -->
          <button id="myBtn">Open Modal</button>
      </div>
    <!-- Trigger/Open The Modal -->
  
    <div class="display">
    <% @sorted_content.select{|item| item.board_id == board.id}.each do |content| %>
      <% if content.class == Link %>
         <div class="content">
          <div><%= image_tag content.img_source, :class => "style_image" %></div>
          <div><%= content.title %></div>
          <div><%= content.created_at %></div>
          <div><%= link_to 'Show', board_link_path(board, content) %></div>
        </div>
      <% elsif content.class == Video %>
       <div class="content">
          <div><%= image_tag content.larger_thumbnail, :class => "style_image" %></div>
          <div><%= content.title %></div>
          <div><%= content.created_at %></div>
          <div><%= link_to 'Show', board_video_path(board, content) %></div>
        </div>
      <% elsif content.class == Post %>
        <div class="content postStyle">
          <div><h3><%=  content.title %></h3></div>
          <div><%=  content.source %> </div>
          <div><%= link_to 'Show', board_post_path(board, content) %> </div>
        </div>
      <% else %>
        <div> else </div>
      <% end %>
    <% end %>

    
 
    </div> <!-- End of board config -->
  </section> 
  </div> <!-- End of board config -->

<% end %>
</article>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>